# Initial main workflow for basic CI checks on all Push/Pull Request events
# Initial goals:
# - [x] Ensure CI is functional
# - [x] Run a simple markdown check using Prettier
# - [x] Run a simple YAML lint check using yamllint
name: Main Lint
# Trigger on push and pull request events
on: [push, pull_request]

permissions:
  # Allow read access, no write permissions
  contents: read

concurrency:
  # one run per branch/PR ref
  group: main-lint-${{ github.ref }}
  # cancel older in-progress runs
  cancel-in-progress: true

# Workflow (made up of one or more jobs, these can run in parallel or sequentially)
jobs:
  markdown:
    name: Markdown format (Prettier)
    # run on the latest Ubuntu environment, Kubernetes to be used in MoJ Stack
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repo
        uses: actions/checkout@v4
      # Run a simple test to ensure CI is functional
      - name: Setup Node (for Prettier)
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      # Check markdown formatting using Prettier
      - name: Check Markdown formatting
        run: npx --yes prettier --check '**/*.md'

  yaml:
    name: YAML lint (yamllint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install "yamllint==1.35.1"

      - name: Run yamllint (workflows only)
        run: yamllint -s -c .yamllint .github/workflows
      
      